----------------------------------
------------- TABLES -------------
----------------------------------
CREATE TABLE FD12INVADJREQ 
(
  NUXRIAREQ NUMBER NOT NULL 
, NUXREFSN NUMBER NOT NULL 
, CDSTATUS VARCHAR2(1 BYTE) NOT NULL 
, DTTXNORIGIN DATE NOT NULL 
, DTTXNUPDATE DATE NOT NULL 
, NATXNORGUSER VARCHAR2(12 BYTE) NOT NULL 
, NATXNUPDUSER VARCHAR2(12 BYTE) NOT NULL 
, CONSTRAINT FD12INVADJREQ_CONSTR_PK PRIMARY KEY 
  (
    NUXRIAREQ 
  , NUXREFSN 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "TS_SMALL_TABLES" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);


CREATE TABLE FD12INVINTRANS 
(
  NUXRPD NUMBER NOT NULL 
, NUSENATE VARCHAR2(20 BYTE) NOT NULL 
, CDSTATUS VARCHAR2(1 BYTE) 
, DTTXNORIGIN DATE 
, DTTXNUPDATE DATE 
, NATXNORGUSER VARCHAR2(12 BYTE) 
, NATXNUPDUSER VARCHAR2(12 BYTE) 
, CONSTRAINT FD12INVINTRANS_PK PRIMARY KEY 
  (
    NUXRPD 
  , NUSENATE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "TS_SMALL_TABLES" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);


CREATE TABLE FD12INVSIGNS 
(
  NUXRSIGN NUMBER NOT NULL 
, NUXREFEM NUMBER 
, BLSIGN BLOB 
, CDSTATUS VARCHAR2(1 BYTE) 
, DTTXNORIGIN DATE 
, DTTXNUPDATE DATE 
, NATXNORGUSER VARCHAR2(12 BYTE) 
, NATXNUPDUSER VARCHAR2(12 BYTE) 
, CONSTRAINT FD12INVSIGNS_PK PRIMARY KEY 
  (
    NUXRSIGN 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "TS_SMALL_TABLES" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
) 
LOB (BLSIGN) STORE AS SYS_LOB0000277795C00003$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  PCTVERSION 10 
  NOCACHE 
  LOGGING  
);


CREATE TABLE FD12ISSUE 
(
  NUXREFSN NUMBER NOT NULL 
, NUXREFCO NUMBER NOT NULL 
, DTLSTINVNTRY DATE NOT NULL 
, DTTXNORIGIN DATE NOT NULL 
, DTISSUE DATE NOT NULL 
, DTTXNUPDATE DATE NOT NULL 
, CDSTATUS VARCHAR2(1 BYTE) NOT NULL 
, NATXNORGUSER VARCHAR2(12 BYTE) NOT NULL 
, NATXNUPDUSER VARCHAR2(12 BYTE) NOT NULL 
, CDADJUST VARCHAR2(1 BYTE) 
, CDLOCTYPEFRM VARCHAR2(1 BYTE) 
, CDTXNSTATUS VARCHAR2(1 BYTE) 
, CDLOCTYPETO VARCHAR2(1 BYTE) 
, CDORGID VARCHAR2(3 BYTE) 
, CDLOCATTO VARCHAR2(6 BYTE) 
, CDLOCATFROM VARCHAR2(6 BYTE) 
, NUSERIAL VARCHAR2(20 BYTE) 
, DTORIGTAG DATE NOT NULL 
, NUXREFPO NUMBER 
, NUXREFCT NUMBER 
, DTINSTALL DATE 
, CDSPECIAL VARCHAR2(1 BYTE) 
, NUXREFWAR NUMBER 
, CDWARSTAT VARCHAR2(1 BYTE) 
, CDMACHTYPE VARCHAR2(12 BYTE) 
, CDMODELNO VARCHAR2(12 BYTE) 
, ADMAC1 VARCHAR2(12 BYTE) 
, ADMAC2 VARCHAR2(12 BYTE) 
, CDUUID VARCHAR2(36 BYTE) 
, NUXRPD NUMBER 
, NAPICKUPBY VARCHAR2(50 BYTE) 
, NUXRPDORIG NUMBER 
, NARELEASEBY VARCHAR2(90 BYTE) 
, NUXRRELSIGN NUMBER 
, NUXRACCPTSIGN NUMBER 
, NAACCEPTBY VARCHAR2(90 BYTE) 
, NADELIVERBY VARCHAR2(50 BYTE) 
, DTPICKUP DATE 
, DTDELIVERY DATE 
, DEPUCOMMENTS VARCHAR2(4000 BYTE) 
, DEDELCOMMENTS VARCHAR2(4000 BYTE) 
, DTMOBAPPMOV DATE 
, CDMOBAPPMOV VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL 
, NUXREFEM NUMBER 
, NUXRMOAPPVER NUMBER 
, DTMOAPPLASTVER DATE 
, DTASSIGNED DATE 
, DEADDTCOMMENT VARCHAR2(150 BYTE) 
, ADPHONECELL VARCHAR2(14 BYTE) 
) 
LOGGING 
TABLESPACE "TS_SMALL_TABLES" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 11534336 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);


CREATE TABLE FD12NWINVITEM 
(
  NUXRNWINVITEM NUMBER NOT NULL 
, NUSENATE VARCHAR2(6 BYTE) NOT NULL 
, CDCOMMODITY VARCHAR2(15 BYTE) 
, CDLOCATTO VARCHAR2(6 BYTE) 
, CDLOCTYPETO VARCHAR2(1 BYTE) 
, DECOMMENTS VARCHAR2(4000 BYTE) 
, NUXREFCO NUMBER 
, NUXREFSN NUMBER 
, CDACTIVITY VARCHAR2(50 BYTE) 
, DTACCEPTED DATE 
, DTREJECTED DATE 
, NATXNORGUSER VARCHAR2(12 BYTE) NOT NULL 
, DTTXNORIGIN TIMESTAMP(6) NOT NULL 
, NATXNUPDUSER VARCHAR2(12 BYTE) NOT NULL 
, DTTXNUPDATE TIMESTAMP(6) NOT NULL 
, CDSTATUS VARCHAR2(1 BYTE) NOT NULL 
, NUXRPD NUMBER 
, NUXRMOAPPVER NUMBER 
) 
LOGGING 
TABLESPACE "TS_SMALL_TABLES" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);


CREATE TABLE FL12ADJUSTCD 
(
  DTTXNUPDATE DATE NOT NULL 
, DTTXNORIGIN DATE NOT NULL 
, CDADJUST VARCHAR2(1 BYTE) NOT NULL 
, CDADJUSTTYPE VARCHAR2(1 BYTE) NOT NULL 
, CDSTATUS VARCHAR2(1 BYTE) NOT NULL 
, NATXNUPDUSER VARCHAR2(12 BYTE) NOT NULL 
, NATXNORGUSER VARCHAR2(12 BYTE) NOT NULL 
, DEADJUST VARCHAR2(25 BYTE) NOT NULL 
) 
LOGGING 
TABLESPACE "TS_SMALL_TABLES" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);


CREATE TABLE FL12INVREQSTAT 
(
  CDINVREQSTAT VARCHAR2(2 BYTE) NOT NULL 
, DEINVREQSTAT VARCHAR2(500 BYTE) 
, CDSTATUS VARCHAR2(1 BYTE) NOT NULL 
, DTTXNORIGIN DATE NOT NULL 
, DTTXNUPDATE DATE NOT NULL 
, NATXNORGUSER VARCHAR2(12 BYTE) NOT NULL 
, NATXNUPDUSER VARCHAR2(12 BYTE) NOT NULL 
, CONSTRAINT SYS_C00127516 PRIMARY KEY 
  (
    CDINVREQSTAT 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "TS_SMALL_TABLES" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);


CREATE TABLE FL12PPWRKTYP 
(
  CDPPWRKTYP VARCHAR2(3 BYTE) NOT NULL 
, DEPPWRKTYP VARCHAR2(50 BYTE) NOT NULL 
, CDSTATUS VARCHAR2(1 BYTE) NOT NULL 
, DTTXNORIGIN DATE NOT NULL 
, DTTXNUPDATE DATE NOT NULL 
, NATXNORGUSER VARCHAR2(12 BYTE) NOT NULL 
, NATXNUPDUSER VARCHAR2(12 BYTE) NOT NULL 
) 
LOGGING 
TABLESPACE "TS_SMALL_TABLES" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 106496 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);


CREATE TABLE FL12SHIPTYP 
(
  NUXRSHIPTYP NUMBER NOT NULL 
, CDSHIPTYP VARCHAR2(20 BYTE) NOT NULL 
, DESHIPTYP VARCHAR2(50 BYTE) NOT NULL 
, CDSTATUS VARCHAR2(1 BYTE) NOT NULL 
, DTTXNUPDATE DATE NOT NULL 
, DTTXNORIGIN DATE NOT NULL 
, NATXNUPDUSER VARCHAR2(12 BYTE) NOT NULL 
, NATXNORGUSER VARCHAR2(12 BYTE) NOT NULL 
, CONSTRAINT FL12SHIPTYP_PK PRIMARY KEY 
  (
    NUXRSHIPTYP 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "TS_SMALL_TABLES" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 204800 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);


CREATE TABLE FL12VERMTHD 
(
  NUXRVERMTHD NUMBER NOT NULL 
, CDVERMTHD VARCHAR2(20 BYTE) NOT NULL 
, DEVERMTHD VARCHAR2(50 BYTE) NOT NULL 
, CDSTATUS VARCHAR2(1 BYTE) NOT NULL 
, DTTXNUPDATE DATE NOT NULL 
, DTTXNORIGIN DATE NOT NULL 
, NATXNUPDUSER VARCHAR2(12 BYTE) NOT NULL 
, NATXNORGUSER VARCHAR2(12 BYTE) NOT NULL 
, CONSTRAINT FL12VERMTHD_PK PRIMARY KEY 
  (
    NUXRVERMTHD 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "TS_SMALL_TABLES" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 204800 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);


CREATE TABLE FM12COMMODTY 
(
  NUXREFCO NUMBER NOT NULL 
, DTTXNORIGIN DATE NOT NULL 
, DTTXNUPDATE DATE NOT NULL 
, CDSTATUS VARCHAR2(1 BYTE) NOT NULL 
, CDSTOCKITEM VARCHAR2(1 BYTE) NOT NULL 
, CDTYPE VARCHAR2(1 BYTE) NOT NULL 
, CDORDUNIT VARCHAR2(10 BYTE) NOT NULL 
, CDISSUNIT VARCHAR2(10 BYTE) NOT NULL 
, NATXNORGUSER VARCHAR2(12 BYTE) NOT NULL 
, NATXNUPDUSER VARCHAR2(12 BYTE) NOT NULL 
, CDCATEGORY VARCHAR2(15 BYTE) NOT NULL 
, NUREORDERPT NUMBER 
, CDOBJECT VARCHAR2(5 BYTE) 
, DECOMMODITYF VARCHAR2(110 BYTE) 
, NUMAXUNITORD NUMBER 
, NUMAXUNITMON NUMBER 
, NUXREFIT NUMBER 
, CFACCOUNT VARCHAR2(5 BYTE) 
, CDACINSPECT VARCHAR2(1 BYTE) 
, CONSTRAINT M12COMMOK_PK PRIMARY KEY 
  (
    NUXREFCO 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "TS_SMALL_TABLES" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 3145728 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);


CREATE TABLE FM12COMXREF 
(
  NUXREFCO NUMBER NOT NULL 
, DTTXNORIGIN DATE NOT NULL 
, DTTXNUPDATE DATE NOT NULL 
, CDSTATUS VARCHAR2(1 BYTE) NOT NULL 
, NATXNORGUSER VARCHAR2(12 BYTE) NOT NULL 
, NATXNUPDUSER VARCHAR2(12 BYTE) NOT NULL 
, CDCOMMODITY VARCHAR2(15 BYTE) NOT NULL 
, CONSTRAINT M12COMXR1_PK PRIMARY KEY 
  (
    NUXREFCO 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "TS_SMALL_TABLES" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 2097152 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);



CREATE TABLE FM12EMLSUP 
(
  NUXREFEM NUMBER NOT NULL 
, NUXREFEMLSUP NUMBER NOT NULL 
, CDSTATUS VARCHAR2(1 BYTE) NOT NULL 
, NATXNUPDUSER VARCHAR2(12 BYTE) NOT NULL 
, NATXNORGUSER VARCHAR2(12 BYTE) NOT NULL 
, DTTXNUPDATE DATE NOT NULL 
, DTTXNORIGIN DATE NOT NULL 
) 
LOGGING 
TABLESPACE "TS_SMALL_TABLES" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 106496 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);


CREATE TABLE FM12INVADJREQ 
(
  NUINVADJREQ NUMBER NOT NULL 
, NAUSER VARCHAR2(12 BYTE) NOT NULL 
, DTINVADJREQ DATE NOT NULL 
, CDADJUSTED VARCHAR2(1 BYTE) NOT NULL 
, CDINVREQSTATM VARCHAR2(2 BYTE) NOT NULL 
, CDSTATUS VARCHAR2(1 BYTE) NOT NULL 
, DTTXNORIGIN DATE NOT NULL 
, DTTXNUPDATE DATE NOT NULL 
, NATXNORGUSER VARCHAR2(12 BYTE) NOT NULL 
, NATXNUPDUSER VARCHAR2(12 BYTE) NOT NULL 
, DEINVCTRLCMTS VARCHAR2(4000 BYTE) 
, DTPRINT DATE 
, NAPRINTBY VARCHAR2(12 BYTE) 
, NUXREFEMAPR NUMBER 
, DTAPPROVAL DATE 
, CDREQCONFIRM VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL 
, CONSTRAINT SYS_C00127527 PRIMARY KEY 
  (
    NUINVADJREQ 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "TS_SMALL_TABLES" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);



CREATE TABLE FM12INVENTRY 
(
  NUXREFCO NUMBER NOT NULL 
, DTTXNUPDATE DATE NOT NULL 
, DTTXNORIGIN DATE NOT NULL 
, CDSTATUS VARCHAR2(1 BYTE) NOT NULL 
, CDLOCTYPE VARCHAR2(1 BYTE) NOT NULL 
, CDLOCAT VARCHAR2(6 BYTE) NOT NULL 
, NATXNUPDUSER VARCHAR2(12 BYTE) NOT NULL 
, NATXNORGUSER VARCHAR2(12 BYTE) NOT NULL 
, AMQTYOHSTD NUMBER 
) 
LOGGING 
TABLESPACE "TS_SMALL_TABLES" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 4194304 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);



CREATE TABLE FM12INVINTRANS 
(
  NUXRPD NUMBER NOT NULL 
, CDLOCATTO VARCHAR2(6 BYTE) 
, CDLOCATFROM VARCHAR2(6 BYTE) 
, CDINTRANSIT VARCHAR2(1 BYTE) 
, NAPICKUPBY VARCHAR2(50 BYTE) 
, NARELEASEBY VARCHAR2(90 BYTE) 
, NUXRRELSIGN NUMBER 
, CDSTATUS VARCHAR2(1 BYTE) 
, DTTXNORIGIN DATE 
, DTTXNUPDATE DATE 
, NATXNORGUSER VARCHAR2(12 BYTE) 
, NATXNUPDUSER VARCHAR2(12 BYTE) 
, DEPUCOMMENTS VARCHAR2(4000 BYTE) 
, NUXRACCPTSIGN NUMBER 
, NADELIVERBY VARCHAR2(50 BYTE) 
, NAACCEPTBY VARCHAR2(90 BYTE) 
, NUXRPDORIG NUMBER 
, DTPICKUP DATE 
, DTDELIVERY DATE 
, DEDELCOMMENTS VARCHAR2(4000 BYTE) 
, CDLOCTYPEFRM VARCHAR2(1 BYTE) 
, CDLOCTYPETO VARCHAR2(1 BYTE) 
, DESHIPCOMMENTS VARCHAR2(4000 BYTE) 
, DEVERCOMMENTS VARCHAR2(4000 BYTE) 
, NUHELPREF VARCHAR2(10 BYTE) 
, NUXREFEMPPWRK NUMBER 
, NUXRSHIPTYP NUMBER 
, NUXRVERMTHD NUMBER 
, CDPPWRKTYP VARCHAR2(3 BYTE) 
, CONSTRAINT FM12INVINTRANS_PK PRIMARY KEY 
  (
    NUXRPD 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "TS_SMALL_TABLES" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);



CREATE TABLE FM12SENXREF
(
  NUXREFSN NUMBER NOT NULL 
, DTTXNORIGIN DATE NOT NULL 
, DTTXNUPDATE DATE NOT NULL 
, CDSTATUS VARCHAR2(1 BYTE) NOT NULL 
, NUSENATE VARCHAR2(6 BYTE) NOT NULL 
, NATXNORGUSER VARCHAR2(12 BYTE) NOT NULL 
, NATXNUPDUSER VARCHAR2(12 BYTE) NOT NULL 
, CONSTRAINT M12SENXR1_PK PRIMARY KEY 
  (
    NUXREFSN 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "TS_SMALL_TABLES" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 5242880 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);


CREATE TABLE FP12SENXREF 
(
  NUXREFSN NUMBER NOT NULL 
, DTTXNUPDATE DATE NOT NULL 
, NATXNUPDUSER VARCHAR2(12 BYTE) NOT NULL 
) 
LOGGING 
TABLESPACE "TS_SMALL_TABLES" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);



CREATE TABLE IM86MODMENU 
(
  DTTXNORIGIN DATE NOT NULL 
, DTTXNUPDATE DATE NOT NULL 
, CDSTATUS VARCHAR2(1 BYTE) NOT NULL 
, CDORGID VARCHAR2(3 BYTE) NOT NULL 
, NUMODULE VARCHAR2(6 BYTE) NOT NULL 
, CDSECLEVEL VARCHAR2(9 BYTE) NOT NULL 
, DEFRMINT VARCHAR2(10 BYTE) NOT NULL 
, NAUSER VARCHAR2(12 BYTE) NOT NULL 
, NATXNUPDUSER VARCHAR2(12 BYTE) NOT NULL 
, NATXNORGUSER VARCHAR2(12 BYTE) NOT NULL 
) 
LOGGING 
TABLESPACE "TS_SMALL_TABLES" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 655360 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);


CREATE TABLE IM86ORGID 
(
  DTEFFECT DATE NOT NULL 
, DTTXNORIGIN DATE NOT NULL 
, DTTXNUPDATE DATE NOT NULL 
, CDSTATUS VARCHAR2(1 BYTE) NOT NULL 
, CDORGID VARCHAR2(3 BYTE) NOT NULL 
, NAUSER VARCHAR2(12 BYTE) NOT NULL 
, NATXNUPDUSER VARCHAR2(12 BYTE) NOT NULL 
, NATXNORGUSER VARCHAR2(12 BYTE) NOT NULL 
, DTLASTACTIVE DATE 
, CDACTIVE VARCHAR2(1 BYTE) 
, CDEXIT VARCHAR2(1 BYTE) 
, NUMODULE VARCHAR2(6 BYTE) 
, DEFRMINT VARCHAR2(10 BYTE) 
, DTPASSWDSET DATE 
, DTPASSWDEXP DATE 
, IPADDRESS VARCHAR2(16 BYTE) 
, NAMACHINE VARCHAR2(30 BYTE) 
, CDMULTIUSR VARCHAR2(1 BYTE) 
, CONSTRAINT M86ORGIDK_PK PRIMARY KEY 
  (
    NAUSER 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "TS_SMALL_TABLES" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);



CREATE TABLE PM21PERSONN 
(
  NUXREFSV NUMBER NOT NULL 
, NUXREFEM NUMBER NOT NULL 
, MOSALBIWKLY NUMBER NOT NULL 
, DTTXNUPDATE DATE NOT NULL 
, DTAPPOINTTO DATE NOT NULL 
, DTPEREMPTO DATE NOT NULL 
, DTORGEMPLOY DATE NOT NULL 
, DTAPPOINTFRM DATE NOT NULL 
, DTBIRTH DATE NOT NULL 
, DTTXNORIGIN DATE NOT NULL 
, DTPEREMPFRM DATE NOT NULL 
, CDSEX VARCHAR2(1 BYTE) NOT NULL 
, CDDUALEMP VARCHAR2(1 BYTE) NOT NULL 
, CDEMPSTATUS VARCHAR2(1 BYTE) NOT NULL 
, CDMARITAL VARCHAR2(1 BYTE) NOT NULL 
, CDNEGUNIT VARCHAR2(2 BYTE) NOT NULL 
, NATITLE VARCHAR2(4 BYTE) NOT NULL 
, CDSTATPER VARCHAR2(4 BYTE) NOT NULL 
, CDAGENCYPR VARCHAR2(5 BYTE) NOT NULL 
, CDEMPTITLE VARCHAR2(7 BYTE) NOT NULL 
, NATXNUPDUSER VARCHAR2(12 BYTE) NOT NULL 
, NATXNORGUSER VARCHAR2(12 BYTE) NOT NULL 
, ADPHONENUMW VARCHAR2(14 BYTE) NOT NULL 
, ADPHONENUM VARCHAR2(14 BYTE) 
, NAFIRSTSUP VARCHAR2(15 BYTE) NOT NULL 
, NAFIRST VARCHAR2(30 BYTE) NOT NULL 
, NALASTSUP VARCHAR2(20 BYTE) NOT NULL 
, NALAST VARCHAR2(30 BYTE) NOT NULL 
, MOADDCITYTAX NUMBER 
, MOADDYONTAX NUMBER 
, MOSALBIWKLYP NUMBER 
, MOVACHRSPD NUMBER 
, MOHRHRSPD NUMBER 
, NUHRHRSPD NUMBER 
, MOADDFEDTAX NUMBER 
, MOCREDUN NUMBER 
, NUDAYSLOST NUMBER 
, MOPRIORYRTE NUMBER 
, MOLOSTTIME NUMBER 
, NUVACHRSLF NUMBER 
, MOTOTHRSPD NUMBER 
, NUVACHRSPD NUMBER 
, MOAMTEXCEED NUMBER 
, NUMINTOTHRS NUMBER 
, NUMINTOTEND NUMBER 
, MOADDSTATTAX NUMBER 
, DTPAYUPDATE DATE 
, DTW4SIGNED DATE 
, DTENDTE DATE 
, DTDEFLAG DATE 
, DTAGENCYTERM DATE 
, DTI9REC DATE 
, DTTRANMEMREC DATE 
, DTRELCHK DATE 
, DTAPPOINT DATE 
, DTCONTSERV DATE 
, DTLEAVEEND DATE 
, CDCHKDIST VARCHAR2(1 BYTE) 
, CDCERTADD VARCHAR2(1 BYTE) 
, CDDEFLAG VARCHAR2(1 BYTE) 
, CDACCRUE VARCHAR2(1 BYTE) 
, NAMIDINIT VARCHAR2(1 BYTE) 
, CDSTATUS VARCHAR2(1 BYTE) 
, CDMARITALYON VARCHAR2(1 BYTE) 
, CDMARITALNYC VARCHAR2(1 BYTE) 
, CDMARITALST VARCHAR2(1 BYTE) 
, CDMARITALFED VARCHAR2(1 BYTE) 
, CDRELCHK VARCHAR2(1 BYTE) 
, CDAPPCHECK VARCHAR2(1 BYTE) 
, CDIDCARD VARCHAR2(1 BYTE) 
, CDPAYTYPE VARCHAR2(2 BYTE) 
, CDCREDUN VARCHAR2(3 BYTE) 
, CDRESPCTR VARCHAR2(3 BYTE) 
, NUYONTAXEX VARCHAR2(3 BYTE) 
, NUCITYTAXEX VARCHAR2(3 BYTE) 
, NUSTATTAXEX VARCHAR2(3 BYTE) 
, NUFEDTAXEX VARCHAR2(3 BYTE) 
, CDSTATPERP VARCHAR2(4 BYTE) 
, CDAGENCY VARCHAR2(5 BYTE) 
, NULINE VARCHAR2(5 BYTE) 
, CDLOCAT VARCHAR2(6 BYTE) 
, NUPOSITION VARCHAR2(8 BYTE) 
, DEMAILDROP VARCHAR2(10 BYTE) 
, CDRESPCTRHD VARCHAR2(10 BYTE) 
, DETIMELOST VARCHAR2(11 BYTE) 
, DELIMITATION VARCHAR2(30 BYTE) 
, DEDAYSLOST VARCHAR2(30 BYTE) 
, NAEMPLABEL VARCHAR2(36 BYTE) 
, DEHRDAYSPD VARCHAR2(40 BYTE) 
, DETXNNOTEPAY VARCHAR2(60 BYTE) 
, CDDIRECTDEPF VARCHAR2(1 BYTE) 
, CDDIRECTDEPP VARCHAR2(1 BYTE) 
, FFNAFIRST VARCHAR2(30 BYTE) 
, FFNAMIDINIT VARCHAR2(2 BYTE) 
, FFNALAST VARCHAR2(30 BYTE) 
, FFNATITLE VARCHAR2(4 BYTE) 
, FFNASUFFIX VARCHAR2(15 BYTE) 
, NASUFFIX VARCHAR2(15 BYTE) 
, DTDIRECTDEPF DATE 
, CDEMPRECNUM VARCHAR2(1 BYTE) 
, NAEMAIL VARCHAR2(50 BYTE) 
, CDDDTHOLDF VARCHAR2(1 BYTE) 
, NUXREFVE NUMBER 
, MOLAGSAL NUMBER 
, CONSTRAINT M21PERSONN_PK PRIMARY KEY 
  (
    NUXREFEM 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "TS_SMALL_TABLES" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 5242880 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);



CREATE TABLE SASS15018 
(
  DTTXNORIGIN DATE 
, DTTXNUPDATE DATE 
, CDINDB VARCHAR2(1 BYTE) 
, CDSTATUS VARCHAR2(1 BYTE) 
, NUSENATE VARCHAR2(6 BYTE) 
, CDLOCAT VARCHAR2(6 BYTE) 
, NATXNORGUSER VARCHAR2(12 BYTE) 
, NATXNUPDUSER VARCHAR2(12 BYTE) 
) 
LOGGING 
TABLESPACE "TS_SMALL_TABLES" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 2097152 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);



CREATE TABLE SASS_PARAMETERS 
(
  CDPARAMETER VARCHAR2(20 BYTE) NOT NULL 
, DEPARAMETER VARCHAR2(100 BYTE) NOT NULL 
, PARAMVAL VARCHAR2(100 BYTE) NOT NULL 
) 
LOGGING 
TABLESPACE "TS_SMALL_TABLES" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);



CREATE TABLE SL16EMLMSG 
(
  NUXREMLMSG NUMBER NOT NULL 
, CDEMLMSG VARCHAR2(20 BYTE) NOT NULL 
, CDFREQUENCY VARCHAR2(30 BYTE) 
, DTBEGIN DATE 
, DTEND DATE 
, DEEMLMSG VARCHAR2(4000 BYTE) 
, NATXNORGUSER VARCHAR2(20 BYTE) NOT NULL 
, NATXNUPDUSER VARCHAR2(20 BYTE) NOT NULL 
, DTTXNORIGIN DATE NOT NULL 
, DTTXNUPDATE DATE NOT NULL 
, CDACTIVE VARCHAR2(1 BYTE) NOT NULL 
, CDSTATUS VARCHAR2(1 BYTE) NOT NULL 
, NAPROCESS VARCHAR2(30 BYTE) NOT NULL 
, NATYPE VARCHAR2(30 BYTE) NOT NULL 
) 
LOGGING 
TABLESPACE "TS_SMALL_TABLES" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);



CREATE TABLE SL16EMLPARAM 
(
  CDEMAILPARAM VARCHAR2(50 BYTE) NOT NULL 
, DEEMAILPARAM VARCHAR2(500 BYTE) 
, CDSTATUS VARCHAR2(1 BYTE) NOT NULL 
, NATXNORGUSER VARCHAR2(12 BYTE) NOT NULL 
, NATXNUPDUSER VARCHAR2(12 BYTE) NOT NULL 
, DTTXNORIGIN DATE NOT NULL 
, DTTXNUPDATE DATE NOT NULL 
) 
LOGGING 
TABLESPACE "TS_SMALL_TABLES" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);



CREATE TABLE SL16EMLTMPLT 
(
  NUXREMLTMPLT NUMBER NOT NULL 
, CDEMLTMPLT VARCHAR2(50 BYTE) NOT NULL 
, NATXNORGUSER VARCHAR2(12 BYTE) NOT NULL 
, DTTXNORIGIN TIMESTAMP(6) NOT NULL 
, NATXNUPDUSER VARCHAR2(12 BYTE) NOT NULL 
, DTTXNUPDATE TIMESTAMP(6) NOT NULL 
, CDSTATUS VARCHAR2(1 BYTE) NOT NULL 
, DEEMLTMPLT CLOB DEFAULT EMPTY_CLOB() 
, CONSTRAINT SL16EMLTMPLT_PK PRIMARY KEY 
  (
    NUXREMLTMPLT 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "TS_SMALL_TABLES" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
) 
LOB (DEEMLTMPLT) STORE AS SYS_LOB0000178614C00008$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  RETENTION 
  NOCACHE 
  LOGGING  
);



CREATE TABLE SL16LOCATION 
(
  DTTXNORIGIN DATE NOT NULL 
, DTTXNUPDATE DATE NOT NULL 
, CDSTATUS VARCHAR2(1 BYTE) NOT NULL 
, CDLOCTYPE VARCHAR2(1 BYTE) NOT NULL 
, CDOFFTYPE VARCHAR2(1 BYTE) NOT NULL 
, ADSTATE VARCHAR2(2 BYTE) NOT NULL 
, CDLOCAT VARCHAR2(6 BYTE) NOT NULL 
, ADZIPCODE VARCHAR2(10 BYTE) NOT NULL 
, CDRESPCTRHD VARCHAR2(10 BYTE) NOT NULL 
, NATXNORGUSER VARCHAR2(12 BYTE) NOT NULL 
, NATXNUPDUSER VARCHAR2(12 BYTE) NOT NULL 
, DELOCAT VARCHAR2(15 BYTE) NOT NULL 
, ADCITY VARCHAR2(30 BYTE) NOT NULL 
, ADSTREET1 VARCHAR2(30 BYTE) NOT NULL 
, ADSTREET2 VARCHAR2(30 BYTE) 
, FFADSTREET1 VARCHAR2(30 BYTE) 
, FFADSTREET2 VARCHAR2(30 BYTE) 
, FFADCITY VARCHAR2(30 BYTE) 
, ADPHONEEXT VARCHAR2(4 BYTE) 
, ADPHONENUMW VARCHAR2(14 BYTE) 
, ADFAXNUM VARCHAR2(14 BYTE) 
, CDPOSLOC VARCHAR2(4 BYTE) 
) 
LOGGING 
TABLESPACE "TS_SMALL_TABLES" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 262144 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);



CREATE TABLE SL16LOCTYPE 
(
  DTTXNORIGIN DATE NOT NULL 
, DTTXNUPDATE DATE NOT NULL 
, CDLOCTYPE VARCHAR2(1 BYTE) NOT NULL 
, CDSTATUS VARCHAR2(1 BYTE) NOT NULL 
, NATXNORGUSER VARCHAR2(12 BYTE) NOT NULL 
, NATXNUPDUSER VARCHAR2(12 BYTE) NOT NULL 
, DELOCTYPE VARCHAR2(25 BYTE) NOT NULL 
, CONSTRAINT L16LOCTYPE_PK PRIMARY KEY 
  (
    CDLOCTYPE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "TS_SMALL_TABLES" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);



----------------------------------
---------- FOREIGN KEYS ----------
----------------------------------

ALTER TABLE FD12INVADJREQ
ADD CONSTRAINT FD12INVADJREQ_FK FOREIGN KEY
(
  NUXRIAREQ 
)
REFERENCES FM12INVADJREQ
(
  NUINVADJREQ 
)
ENABLE;

ALTER TABLE FD12INVADJREQ
ADD CONSTRAINT FD12INVADJREQ_FK2 FOREIGN KEY
(
  NUXREFSN 
)
REFERENCES FM12SENXREF
(
  NUXREFSN 
)
ENABLE;


ALTER TABLE FD12INVINTRANS
ADD CONSTRAINT FD12INVINTRANS_FM12INVINT_FK1 FOREIGN KEY
(
  NUXRPD 
)
REFERENCES FM12INVINTRANS
(
  NUXRPD 
)
ENABLE;


ALTER TABLE FM12INVADJREQ
ADD CONSTRAINT FM12INVADJREQ_FK FOREIGN KEY
(
  CDINVREQSTATM 
)
REFERENCES FL12INVREQSTAT
(
  CDINVREQSTAT 
)
ENABLE;


ALTER TABLE FM12INVINTRANS
ADD CONSTRAINT FM12INVINTRANS_FK_SHIPTYP FOREIGN KEY
(
  NUXRSHIPTYP 
)
REFERENCES FL12SHIPTYP
(
  NUXRSHIPTYP 
)
ENABLE;

ALTER TABLE FM12INVINTRANS
ADD CONSTRAINT FM12INVINTRANS_FK_VERMTHD FOREIGN KEY
(
  NUXRVERMTHD 
)
REFERENCES FL12VERMTHD
(
  NUXRVERMTHD 
)
ENABLE;

----------------------------------
------------- INDEXES ------------
----------------------------------

CREATE UNIQUE INDEX M12INVENK_UK ON FM12INVENTRY (NUXREFCO ASC, CDLOCAT ASC, CDLOCTYPE ASC) 
LOGGING 
TABLESPACE "TS_SMALL_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 3145728 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);


CREATE UNIQUE INDEX M86MODME1_UK ON IM86MODMENU (NAUSER ASC, NUMODULE ASC, DEFRMINT ASC) 
LOGGING 
TABLESPACE "TS_SMALL_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 524288 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);


CREATE UNIQUE INDEX L16LOCATK_UK ON SL16LOCATION (CDLOCAT ASC, CDLOCTYPE ASC) 
LOGGING 
TABLESPACE "TS_SMALL_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);







