set define off

INSERT INTO SL16LOCATION 
(DTTXNORIGIN, DTTXNUPDATE, CDSTATUS, CDLOCTYPE, CDOFFTYPE, ADSTATE, CDLOCAT, ADZIPCODE, 
CDRESPCTRHD, NATXNORGUSER, NATXNUPDUSER, DELOCAT, ADCITY, ADSTREET1, ADSTREET2, FFADSTREET1, 
FFADSTREET2, FFADCITY, ADPHONEEXT, ADPHONENUMW, ADFAXNUM, CDPOSLOC) 
VALUES(to_date('14-APR-99', 'DD-MON-RR'), to_date('11-MAR-08', 'DD-MON-RR'), 'A', 'W', 'A', 'NY', 'A42FB', 12247, 'STSBAC', 'CASEIRAS', 'CASEIRAS', '2ND FLOOR, AG4', 'ALBANY',
'2ND FLOOR, AGENCY BLDG 4', '','2nd Floor, Agency Bldg 4', '', 'Albany','','','','');


INSERT INTO SL16LOCATION 
(DTTXNORIGIN, DTTXNUPDATE, CDSTATUS, CDLOCTYPE, CDOFFTYPE, ADSTATE, CDLOCAT, ADZIPCODE, 
CDRESPCTRHD, NATXNORGUSER, NATXNUPDUSER, DELOCAT, ADCITY, ADSTREET1, ADSTREET2, FFADSTREET1, 
FFADSTREET2, FFADCITY, ADPHONEEXT, ADPHONENUMW, ADFAXNUM, CDPOSLOC) 
VALUES(to_date('14-APR-99', 'DD-MON-RR'), to_date('22-APR-12', 'DD-MON-RR'), 'A', 'W', 'A', 'NY', 'L711B', 12247, 'RICHIE', 'CASEIRAS', 'CASEIRAS', 'RM 321B LOB', 'ALBANY',
'RM 321B LOB', '','RM 321B LOB', '', 'Albany','','','','');

INSERT INTO SL16LOCATION 
(DTTXNORIGIN, DTTXNUPDATE, CDSTATUS, CDLOCTYPE, CDOFFTYPE, ADSTATE, CDLOCAT, ADZIPCODE, 
CDRESPCTRHD, NATXNORGUSER, NATXNUPDUSER, DELOCAT, ADCITY, ADSTREET1, ADSTREET2, FFADSTREET1, 
FFADSTREET2, FFADCITY, ADPHONEEXT, ADPHONENUMW, ADFAXNUM, CDPOSLOC) 
VALUES(to_date('14-APR-99', 'DD-MON-RR'), to_date('22-APR-12', 'DD-MON-RR'), 'A', 'S', 'A', 'NY', 'L711B', 12247, 'RICHIE', 'CASEIRAS', 'CASEIRAS', 'RM 321B LOB', 'ALBANY',
'RM 321B LOB', '','RM 321B LOB', '', 'Albany','','','','');

INSERT INTO SL16LOCATION 
(DTTXNORIGIN, DTTXNUPDATE, CDSTATUS, CDLOCTYPE, CDOFFTYPE, ADSTATE, CDLOCAT, ADZIPCODE, 
CDRESPCTRHD, NATXNORGUSER, NATXNUPDUSER, DELOCAT, ADCITY, ADSTREET1, ADSTREET2, FFADSTREET1, 
FFADSTREET2, FFADCITY, ADPHONEEXT, ADPHONENUMW, ADFAXNUM, CDPOSLOC) 
VALUES( to_date('14-APR-99', 'DD-MON-RR'), to_date('11-DEC-14', 'DD-MON-RR'), 'A', 'W', 'D', 'NY', 'D55001', 14625, 'THOMAS', 'CASEIRAS', 'CASEIRAS', '838 YELLOW', 'ROCHESTER',
'838 YELLOW', '', '838 YELLOW', '', 'Rochester', 1011, '', '', '');


INSERT INTO SL16LOCATION 
(DTTXNORIGIN, DTTXNUPDATE, CDSTATUS, CDLOCTYPE, CDOFFTYPE, ADSTATE, CDLOCAT, ADZIPCODE, 
CDRESPCTRHD, NATXNORGUSER, NATXNUPDUSER, DELOCAT, ADCITY, ADSTREET1, ADSTREET2, FFADSTREET1, 
FFADSTREET2, FFADCITY, ADPHONEEXT, ADPHONENUMW, ADFAXNUM, CDPOSLOC) 
VALUES(to_date('14-APR-99', 'DD-MON-RR'), to_date('12-NOV-13', 'DD-MON-RR'), 'A', 'W', 'A', 'NY', 'CAP125', 17233, 'SMITH', 'CASEIRAS', 'CASEIRAS', '11 WASH STREET', 'BUFFALO',
'11 WASHINGTON STREET', '', '11 WASHINGTON STREET', '', 'BUFFALO', 181, '', '', '');





Insert into FL12ADJUSTCD (DTTXNUPDATE,DTTXNORIGIN,CDADJUST,CDADJUSTTYPE,CDSTATUS,NATXNUPDUSER,NATXNORGUSER,DEADJUST) values (to_date('02-OCT-92','DD-MON-RR'),to_date('04-MAR-92','DD-MON-RR'),'O','S','A','SFMSPROD','SFMSPROD','SURPLUS/SOLD');
Insert into FL12ADJUSTCD (DTTXNUPDATE,DTTXNORIGIN,CDADJUST,CDADJUSTTYPE,CDSTATUS,NATXNUPDUSER,NATXNORGUSER,DEADJUST) values (to_date('21-DEC-93','DD-MON-RR'),to_date('21-DEC-93','DD-MON-RR'),'V','D','A','SFMSPROD','SFMSPROD','RETURN TO VEND/WAREHOUSE');
Insert into FL12ADJUSTCD (DTTXNUPDATE,DTTXNORIGIN,CDADJUST,CDADJUSTTYPE,CDSTATUS,NATXNUPDUSER,NATXNORGUSER,DEADJUST) values (to_date('24-JAN-96','DD-MON-RR'),to_date('21-DEC-93','DD-MON-RR'),'W','M','A','SFMSPROD','SFMSPROD','CREATED FOR INV. PURPOSES');
Insert into FL12ADJUSTCD (DTTXNUPDATE,DTTXNORIGIN,CDADJUST,CDADJUSTTYPE,CDSTATUS,NATXNUPDUSER,NATXNORGUSER,DEADJUST) values (to_date('30-OCT-91','DD-MON-RR'),to_date('30-OCT-91','DD-MON-RR'),'P','M','A','SFMSPROD','SFMSPROD','PHYSICAL INVENTORY');
Insert into FL12ADJUSTCD (DTTXNUPDATE,DTTXNORIGIN,CDADJUST,CDADJUSTTYPE,CDSTATUS,NATXNUPDUSER,NATXNORGUSER,DEADJUST) values (to_date('30-OCT-91','DD-MON-RR'),to_date('30-OCT-91','DD-MON-RR'),'F','A','A','SFMSPROD','SFMSPROD','FOUND ON SITE');
Insert into FL12ADJUSTCD (DTTXNUPDATE,DTTXNORIGIN,CDADJUST,CDADJUSTTYPE,CDSTATUS,NATXNUPDUSER,NATXNORGUSER,DEADJUST) values (to_date('25-JAN-96','DD-MON-RR'),to_date('30-OCT-91','DD-MON-RR'),'L','S','A','SFMSPROD','SFMSPROD','LOST/CONVERSION TO SFMS');
Insert into FL12ADJUSTCD (DTTXNUPDATE,DTTXNORIGIN,CDADJUST,CDADJUSTTYPE,CDSTATUS,NATXNUPDUSER,NATXNORGUSER,DEADJUST) values (to_date('30-OCT-91','DD-MON-RR'),to_date('30-OCT-91','DD-MON-RR'),'R','A','A','SFMSPROD','SFMSPROD','RECOVERED');
Insert into FL12ADJUSTCD (DTTXNUPDATE,DTTXNORIGIN,CDADJUST,CDADJUSTTYPE,CDSTATUS,NATXNUPDUSER,NATXNORGUSER,DEADJUST) values (to_date('30-OCT-91','DD-MON-RR'),to_date('30-OCT-91','DD-MON-RR'),'J','S','A','SFMSPROD','SFMSPROD','JUNKED BEYOND REPAIR');
Insert into FL12ADJUSTCD (DTTXNUPDATE,DTTXNORIGIN,CDADJUST,CDADJUSTTYPE,CDSTATUS,NATXNUPDUSER,NATXNORGUSER,DEADJUST) values (to_date('30-OCT-91','DD-MON-RR'),to_date('30-OCT-91','DD-MON-RR'),'S','S','A','SFMSPROD','SFMSPROD','STOLEN');
Insert into FL12ADJUSTCD (DTTXNUPDATE,DTTXNORIGIN,CDADJUST,CDADJUSTTYPE,CDSTATUS,NATXNUPDUSER,NATXNORGUSER,DEADJUST) values (to_date('30-OCT-91','DD-MON-RR'),to_date('30-OCT-91','DD-MON-RR'),'E','S','A','SFMSPROD','SFMSPROD','ERROR');
Insert into FL12ADJUSTCD (DTTXNUPDATE,DTTXNORIGIN,CDADJUST,CDADJUSTTYPE,CDSTATUS,NATXNUPDUSER,NATXNORGUSER,DEADJUST) values (to_date('30-OCT-91','DD-MON-RR'),to_date('30-OCT-91','DD-MON-RR'),'T','S','A','SFMSPROD','SFMSPROD','TRANSFERRED');


Insert into FL12INVREQSTAT (CDINVREQSTAT,DEINVREQSTAT,CDSTATUS,DTTXNORIGIN,DTTXNUPDATE,NATXNORGUSER,NATXNUPDUSER) values ('PE','Pending user review','A',to_date('16-JUL-14','DD-MON-RR'),to_date('16-JUL-14','DD-MON-RR'),'CASEIRAS','CASEIRAS');
Insert into FL12INVREQSTAT (CDINVREQSTAT,DEINVREQSTAT,CDSTATUS,DTTXNORIGIN,DTTXNUPDATE,NATXNORGUSER,NATXNUPDUSER) values ('SI','Submitted to Inventory Control','A',to_date('04-AUG-14','DD-MON-RR'),to_date('04-AUG-14','DD-MON-RR'),'CASEIRAS','CASEIRAS');
Insert into FL12INVREQSTAT (CDINVREQSTAT,DEINVREQSTAT,CDSTATUS,DTTXNORIGIN,DTTXNUPDATE,NATXNORGUSER,NATXNUPDUSER) values ('SM','Submitted to Maint & Oper Mgnt','A',to_date('04-AUG-14','DD-MON-RR'),to_date('14-OCT-14','DD-MON-RR'),'CASEIRAS','SASS_OWNER');
Insert into FL12INVREQSTAT (CDINVREQSTAT,DEINVREQSTAT,CDSTATUS,DTTXNORIGIN,DTTXNUPDATE,NATXNORGUSER,NATXNUPDUSER) values ('AP','Approved','A',to_date('04-AUG-14','DD-MON-RR'),to_date('04-AUG-14','DD-MON-RR'),'CASEIRAS','CASEIRAS');
Insert into FL12INVREQSTAT (CDINVREQSTAT,DEINVREQSTAT,CDSTATUS,DTTXNORIGIN,DTTXNUPDATE,NATXNORGUSER,NATXNUPDUSER) values ('RJ','Rejected','A',to_date('04-AUG-14','DD-MON-RR'),to_date('04-AUG-14','DD-MON-RR'),'CASEIRAS','CASEIRAS');
Insert into FL12INVREQSTAT (CDINVREQSTAT,DEINVREQSTAT,CDSTATUS,DTTXNORIGIN,DTTXNUPDATE,NATXNORGUSER,NATXNUPDUSER) values ('CA','Canceled','A',to_date('04-AUG-14','DD-MON-RR'),to_date('04-AUG-14','DD-MON-RR'),'CASEIRAS','CASEIRAS');



Insert into FL12PPWRKTYP (CDPPWRKTYP,DEPPWRKTYP,CDSTATUS,DTTXNORIGIN,DTTXNUPDATE,NATXNORGUSER,NATXNUPDUSER) values ('RPK','Remote Pickup Paperwork Indicator','A',to_date('02-APR-14','DD-MON-RR'),to_date('02-APR-14','DD-MON-RR'),'SASS_OWNER','SASS_OWNER');
Insert into FL12PPWRKTYP (CDPPWRKTYP,DEPPWRKTYP,CDSTATUS,DTTXNORIGIN,DTTXNUPDATE,NATXNORGUSER,NATXNUPDUSER) values ('RDL','Remote Delivery Paperwork Indicator','A',to_date('02-APR-14','DD-MON-RR'),to_date('02-APR-14','DD-MON-RR'),'SASS_OWNER','SASS_OWNER');


Insert into FL12SHIPTYP (NUXRSHIPTYP,CDSHIPTYP,DESHIPTYP,CDSTATUS,DTTXNUPDATE,DTTXNORIGIN,NATXNUPDUSER,NATXNORGUSER) values (1,'UPS','United Parcel Service','A',to_date('07-NOV-13','DD-MON-RR'),to_date('07-NOV-13','DD-MON-RR'),'CASEIRAS','CASEIRAS');
Insert into FL12SHIPTYP (NUXRSHIPTYP,CDSHIPTYP,DESHIPTYP,CDSTATUS,DTTXNUPDATE,DTTXNORIGIN,NATXNUPDUSER,NATXNORGUSER) values (2,'FedEx','FedEx Corporation','A',to_date('07-NOV-13','DD-MON-RR'),to_date('07-NOV-13','DD-MON-RR'),'CASEIRAS','CASEIRAS');
Insert into FL12SHIPTYP (NUXRSHIPTYP,CDSHIPTYP,DESHIPTYP,CDSTATUS,DTTXNUPDATE,DTTXNORIGIN,NATXNUPDUSER,NATXNORGUSER) values (3,'Maintenance','Maintenance Staff','A',to_date('07-NOV-13','DD-MON-RR'),to_date('07-NOV-13','DD-MON-RR'),'CASEIRAS','CASEIRAS');
Insert into FL12SHIPTYP (NUXRSHIPTYP,CDSHIPTYP,DESHIPTYP,CDSTATUS,DTTXNUPDATE,DTTXNORIGIN,NATXNUPDUSER,NATXNORGUSER) values (4,'Other','Other','A',to_date('07-NOV-13','DD-MON-RR'),to_date('07-NOV-13','DD-MON-RR'),'CASEIRAS','CASEIRAS');




Insert into FL12VERMTHD (NUXRVERMTHD,CDVERMTHD,DEVERMTHD,CDSTATUS,DTTXNUPDATE,DTTXNORIGIN,NATXNUPDUSER,NATXNORGUSER) values (1,'Paperwork','Paperwork Received','A',to_date('07-NOV-13','DD-MON-RR'),to_date('07-NOV-13','DD-MON-RR'),'CASEIRAS','CASEIRAS');
Insert into FL12VERMTHD (NUXRVERMTHD,CDVERMTHD,DEVERMTHD,CDSTATUS,DTTXNUPDATE,DTTXNORIGIN,NATXNUPDUSER,NATXNORGUSER) values (3,'OSR','Verified by OSR','A',to_date('20-NOV-13','DD-MON-RR'),to_date('20-NOV-13','DD-MON-RR'),'CASEIRAS','CASEIRAS');
Insert into FL12VERMTHD (NUXRVERMTHD,CDVERMTHD,DEVERMTHD,CDSTATUS,DTTXNUPDATE,DTTXNORIGIN,NATXNUPDUSER,NATXNORGUSER) values (4,'Phone','Verified by phone call','A',to_date('20-NOV-13','DD-MON-RR'),to_date('20-NOV-13','DD-MON-RR'),'CASEIRAS','CASEIRAS');
Insert into FL12VERMTHD (NUXRVERMTHD,CDVERMTHD,DEVERMTHD,CDSTATUS,DTTXNUPDATE,DTTXNORIGIN,NATXNUPDUSER,NATXNORGUSER) values (5,'Other','Other','A',to_date('20-NOV-13','DD-MON-RR'),to_date('20-NOV-13','DD-MON-RR'),'CASEIRAS','CASEIRAS');



Insert into SL16LOCTYPE (DTTXNORIGIN,DTTXNUPDATE,CDLOCTYPE,CDSTATUS,NATXNORGUSER,NATXNUPDUSER,DELOCTYPE) values (to_date('17-MAR-92','DD-MON-RR'),to_date('17-MAR-92','DD-MON-RR'),'H','A','SFMSPROD','SFMSPROD','WAREHOUSE LOCATION');
Insert into SL16LOCTYPE (DTTXNORIGIN,DTTXNUPDATE,CDLOCTYPE,CDSTATUS,NATXNORGUSER,NATXNUPDUSER,DELOCTYPE) values (to_date('17-MAR-92','DD-MON-RR'),to_date('17-MAR-92','DD-MON-RR'),'S','A','SFMSPROD','SFMSPROD','STORAGE LOCATION');
Insert into SL16LOCTYPE (DTTXNORIGIN,DTTXNUPDATE,CDLOCTYPE,CDSTATUS,NATXNORGUSER,NATXNUPDUSER,DELOCTYPE) values (to_date('17-MAR-92','DD-MON-RR'),to_date('17-MAR-92','DD-MON-RR'),'P','A','SFMSPROD','SFMSPROD','SUPPLY LOCATION');
Insert into SL16LOCTYPE (DTTXNORIGIN,DTTXNUPDATE,CDLOCTYPE,CDSTATUS,NATXNORGUSER,NATXNUPDUSER,DELOCTYPE) values (to_date('17-MAR-92','DD-MON-RR'),to_date('17-MAR-92','DD-MON-RR'),'W','A','SFMSPROD','SFMSPROD','WORK LOCATION');


Insert into FM12COMMODTY (NUXREFCO,DTTXNORIGIN,DTTXNUPDATE,CDSTATUS,CDSTOCKITEM,CDTYPE,CDORDUNIT,CDISSUNIT,NATXNORGUSER,NATXNUPDUSER,CDCATEGORY,DECOMMODITYF) values (200,to_date('22-MAR-99','DD-MON-RR'),to_date('11-SEP-04','DD-MON-RR'),'A','N','I','EACH',1,'CASEIRAS','CASEIRAS','COMPUTER','LENOVO DESKTOP COMPUTER');
Insert into FM12COMMODTY (NUXREFCO,DTTXNORIGIN,DTTXNUPDATE,CDSTATUS,CDSTOCKITEM,CDTYPE,CDORDUNIT,CDISSUNIT,NATXNORGUSER,NATXNUPDUSER,CDCATEGORY,DECOMMODITYF) values (201,to_date('11-MAR-92','DD-MON-RR'),to_date('22-OCT-12','DD-MON-RR'),'A','N','E','EACH','DOZEN','CASEIRAS','CASEIRAS','PEN','BLUE INK PEN');
Insert into FM12COMMODTY (NUXREFCO,DTTXNORIGIN,DTTXNUPDATE,CDSTATUS,CDSTOCKITEM,CDTYPE,CDORDUNIT,CDISSUNIT,NATXNORGUSER,NATXNUPDUSER,CDCATEGORY,DECOMMODITYF) values (202,to_date('17-FEB-99','DD-MON-RR'),to_date('28-MAY-11','DD-MON-RR'),'A','N','I','EACH',1,'CASEIRAS','CASEIRAS','ELEC/WIRE','ROMEX WIRE 10-3 W.G.');
Insert into FM12COMMODTY (NUXREFCO,DTTXNORIGIN,DTTXNUPDATE,CDSTATUS,CDSTOCKITEM,CDTYPE,CDORDUNIT,CDISSUNIT,NATXNORGUSER,NATXNUPDUSER,CDCATEGORY,DECOMMODITYF) values (203,to_date('08-JAN-08','DD-MON-RR'),to_date('05-DEC-10','DD-MON-RR'),'A','N','I','EACH',1,'CASEIRAS','CASEIRAS','CHAIN','CHAIR SENATOR HI BACK CHAMBER');

Insert into FM12COMXREF (NUXREFCO,DTTXNORIGIN,DTTXNUPDATE,CDSTATUS,NATXNORGUSER,NATXNUPDUSER,CDCOMMODITY) values (200,to_date('22-MAR-99','DD-MON-RR'),to_date('11-SEP-04','DD-MON-RR'),'A','CASEIRAS','CASEIRAS','BMOELIB');
Insert into FM12COMXREF (NUXREFCO,DTTXNORIGIN,DTTXNUPDATE,CDSTATUS,NATXNORGUSER,NATXNUPDUSER,CDCOMMODITY) values (201,to_date('22-MAR-99','DD-MON-RR'),to_date('11-SEP-04','DD-MON-RR'),'A','CASEIRAS','CASEIRAS','BLANAM1250');
Insert into FM12COMXREF (NUXREFCO,DTTXNORIGIN,DTTXNUPDATE,CDSTATUS,NATXNORGUSER,NATXNUPDUSER,CDCOMMODITY) values (202,to_date('22-MAR-99','DD-MON-RR'),to_date('11-SEP-04','DD-MON-RR'),'A','CASEIRAS','CASEIRAS','BLANCONDHM');
Insert into FM12COMXREF (NUXREFCO,DTTXNORIGIN,DTTXNUPDATE,CDSTATUS,NATXNORGUSER,NATXNUPDUSER,CDCOMMODITY) values (203,to_date('22-MAR-99','DD-MON-RR'),to_date('11-SEP-04','DD-MON-RR'),'A','CASEIRAS','CASEIRAS','BLANDAY500');


Insert into FM12INVADJREQ (NUINVADJREQ,NAUSER,DTINVADJREQ,CDADJUSTED,CDINVREQSTATM,CDSTATUS,DTTXNORIGIN,DTTXNUPDATE,NATXNORGUSER,NATXNUPDUSER) values (1,'CASEIRAS',to_date('22-MAR-99','DD-MON-RR'),'S', 'PE','A',to_date('22-MAR-99','DD-MON-RR'),to_date('22-MAR-99','DD-MON-RR'),'CASEIRAS','CASEIRAS');
Insert into FM12INVADJREQ (NUINVADJREQ,NAUSER,DTINVADJREQ,CDADJUSTED,CDINVREQSTATM,CDSTATUS,DTTXNORIGIN,DTTXNUPDATE,NATXNORGUSER,NATXNUPDUSER) values (2,'CASEIRAS',to_date('22-MAR-99','DD-MON-RR'),'O', 'PE','A',to_date('22-MAR-99','DD-MON-RR'),to_date('22-MAR-99','DD-MON-RR'),'CASEIRAS','CASEIRAS');
Insert into FM12INVADJREQ (NUINVADJREQ,NAUSER,DTINVADJREQ,CDADJUSTED,CDINVREQSTATM,CDSTATUS,DTTXNORIGIN,DTTXNUPDATE,NATXNORGUSER,NATXNUPDUSER) values (3,'CASEIRAS',to_date('22-MAR-99','DD-MON-RR'),'L', 'PE','A',to_date('22-MAR-99','DD-MON-RR'),to_date('22-MAR-99','DD-MON-RR'),'CASEIRAS','CASEIRAS');
Insert into FM12INVADJREQ (NUINVADJREQ,NAUSER,DTINVADJREQ,CDADJUSTED,CDINVREQSTATM,CDSTATUS,DTTXNORIGIN,DTTXNUPDATE,NATXNORGUSER,NATXNUPDUSER) values (4,'CASEIRAS',to_date('22-MAR-99','DD-MON-RR'),'J', 'RJ','A',to_date('22-MAR-99','DD-MON-RR'),to_date('22-MAR-99','DD-MON-RR'),'CASEIRAS','CASEIRAS');
Insert into FM12INVADJREQ (NUINVADJREQ,NAUSER,DTINVADJREQ,CDADJUSTED,CDINVREQSTATM,CDSTATUS,DTTXNORIGIN,DTTXNUPDATE,NATXNORGUSER,NATXNUPDUSER) values (5,'CASEIRAS',to_date('22-MAR-99','DD-MON-RR'),'S', 'SM','A',to_date('22-MAR-99','DD-MON-RR'),to_date('22-MAR-99','DD-MON-RR'),'CASEIRAS','CASEIRAS');


Insert into IM86MODMENU (DTTXNORIGIN,DTTXNUPDATE,CDSTATUS,CDORGID,NUMODULE,CDSECLEVEL,DEFRMINT,NAUSER,NATXNUPDUSER,NATXNORGUSER) values (to_date('22-MAR-99','DD-MON-RR'),to_date('22-MAR-99','DD-MON-RR'),'A','ALL','F01200',1,'FMINVMA12','INVENTORY','INVENTORY','INVENTORY');


Insert into IM86ORGID (DTEFFECT, DTTXNORIGIN, DTTXNUPDATE,CDSTATUS,CDORGID,NAUSER,NATXNUPDUSER,NATXNORGUSER,DTLASTACTIVE,NUMODULE,DTPASSWDSET,DTPASSWDEXP) values (to_date('22-MAR-99','DD-MON-RR'),to_date('22-MAR-99','DD-MON-RR'),to_date('22-MAR-99','DD-MON-RR'),'A','ALL','INVENTORY','INVENTORY','INVENTORY',to_date('22-MAR-99','DD-MON-RR'),'S08600',to_date('22-MAR-99','DD-MON-RR'),to_date('22-MAR-20','DD-MON-RR'));

Insert into SASS_PARAMETERS (CDPARAMETER,DEPARAMETER,PARAMVAL) values ('PASSWD_WARNING','PASSWORD WARNING IN DAYS',10);

Insert into PM21PERSONN (NUXREFSV,NUXREFEM,MOSALBIWKLY,DTTXNUPDATE,DTAPPOINTTO,DTPEREMPTO,DTORGEMPLOY,DTAPPOINTFRM,DTBIRTH,DTTXNORIGIN,DTPEREMPFRM,CDSEX,CDDUALEMP,CDEMPSTATUS,CDMARITAL,CDNEGUNIT,NATITLE,CDSTATPER,CDAGENCYPR,CDEMPTITLE,NATXNUPDUSER,NATXNORGUSER,ADPHONENUMW,ADPHONENUM,NAFIRSTSUP,NAFIRST,NALASTSUP,NALAST) values (9900, 12212, 1111, to_date('22-MAR-99','DD-MON-RR'),to_date('22-MAR-99','DD-MON-RR'),to_date('22-MAR-99','DD-MON-RR'),to_date('22-MAR-99','DD-MON-RR'),to_date('22-MAR-99','DD-MON-RR'),to_date('22-MAR-66','DD-MON-RR'),to_date('22-MAR-99','DD-MON-RR'),to_date('22-MAR-99','DD-MON-RR'),'M','N','A','M',32,'MR','ACT',23211,92819,'JOHNSON','JOHNSON','(518)111-111','518-111-2222','WILLIAM','KEVIN','SMITH','CASEIRAS')


Insert into FM12SENXREF (NUXREFSN,DTTXNORIGIN,DTTXNUPDATE,CDSTATUS,NUSENATE,NATXNORGUSER,NATXNUPDUSER) values (700, to_date('22-MAR-99','DD-MON-RR'),to_date('22-MAR-99','DD-MON-RR'),'A','000754','SFMSTEST','SFMSTEST');
Insert into FM12SENXREF (NUXREFSN,DTTXNORIGIN,DTTXNUPDATE,CDSTATUS,NUSENATE,NATXNORGUSER,NATXNUPDUSER) values (701, to_date('22-MAR-99','DD-MON-RR'),to_date('22-MAR-99','DD-MON-RR'),'A','000755','SFMSTEST','SFMSTEST');
Insert into FM12SENXREF (NUXREFSN,DTTXNORIGIN,DTTXNUPDATE,CDSTATUS,NUSENATE,NATXNORGUSER,NATXNUPDUSER) values (702, to_date('22-MAR-99','DD-MON-RR'),to_date('22-MAR-99','DD-MON-RR'),'A','000756','SFMSTEST','SFMSTEST');
Insert into FM12SENXREF (NUXREFSN,DTTXNORIGIN,DTTXNUPDATE,CDSTATUS,NUSENATE,NATXNORGUSER,NATXNUPDUSER) values (703, to_date('22-MAR-99','DD-MON-RR'),to_date('22-MAR-99','DD-MON-RR'),'A','000757','SFMSTEST','SFMSTEST');
Insert into FM12SENXREF (NUXREFSN,DTTXNORIGIN,DTTXNUPDATE,CDSTATUS,NUSENATE,NATXNORGUSER,NATXNUPDUSER) values (704, to_date('22-MAR-99','DD-MON-RR'),to_date('22-MAR-99','DD-MON-RR'),'A','000758','SFMSTEST','SFMSTEST');
Insert into FM12SENXREF (NUXREFSN,DTTXNORIGIN,DTTXNUPDATE,CDSTATUS,NUSENATE,NATXNORGUSER,NATXNUPDUSER) values (705, to_date('22-MAR-99','DD-MON-RR'),to_date('22-MAR-99','DD-MON-RR'),'A','000759','SFMSTEST','SFMSTEST');
Insert into FM12SENXREF (NUXREFSN,DTTXNORIGIN,DTTXNUPDATE,CDSTATUS,NUSENATE,NATXNORGUSER,NATXNUPDUSER) values (706, to_date('22-MAR-99','DD-MON-RR'),to_date('22-MAR-99','DD-MON-RR'),'A','000760','SFMSTEST','SFMSTEST');
Insert into FM12SENXREF (NUXREFSN,DTTXNORIGIN,DTTXNUPDATE,CDSTATUS,NUSENATE,NATXNORGUSER,NATXNUPDUSER) values (707, to_date('22-MAR-99','DD-MON-RR'),to_date('22-MAR-99','DD-MON-RR'),'A','000761','SFMSTEST','SFMSTEST');
Insert into FM12SENXREF (NUXREFSN,DTTXNORIGIN,DTTXNUPDATE,CDSTATUS,NUSENATE,NATXNORGUSER,NATXNUPDUSER) values (708, to_date('22-MAR-99','DD-MON-RR'),to_date('22-MAR-99','DD-MON-RR'),'A','000762','SFMSTEST','SFMSTEST');
Insert into FM12SENXREF (NUXREFSN,DTTXNORIGIN,DTTXNUPDATE,CDSTATUS,NUSENATE,NATXNORGUSER,NATXNUPDUSER) values (709, to_date('22-MAR-99','DD-MON-RR'),to_date('22-MAR-99','DD-MON-RR'),'A','000763','SFMSTEST','SFMSTEST');
Insert into FM12SENXREF (NUXREFSN,DTTXNORIGIN,DTTXNUPDATE,CDSTATUS,NUSENATE,NATXNORGUSER,NATXNUPDUSER) values (710, to_date('22-MAR-99','DD-MON-RR'),to_date('22-MAR-99','DD-MON-RR'),'A','000764','SFMSTEST','SFMSTEST');
Insert into FM12SENXREF (NUXREFSN,DTTXNORIGIN,DTTXNUPDATE,CDSTATUS,NUSENATE,NATXNORGUSER,NATXNUPDUSER) values (3354, to_date('22-MAR-99','DD-MON-RR'),to_date('22-MAR-99','DD-MON-RR'),'A','003516','SFMSTEST','SFMSTEST');
Insert into FM12SENXREF (NUXREFSN,DTTXNORIGIN,DTTXNUPDATE,CDSTATUS,NUSENATE,NATXNORGUSER,NATXNUPDUSER) values (3355, to_date('22-MAR-99','DD-MON-RR'),to_date('22-MAR-99','DD-MON-RR'),'A','003517','SFMSTEST','SFMSTEST');
Insert into FM12SENXREF (NUXREFSN,DTTXNORIGIN,DTTXNUPDATE,CDSTATUS,NUSENATE,NATXNORGUSER,NATXNUPDUSER) values (3356, to_date('22-MAR-99','DD-MON-RR'),to_date('22-MAR-99','DD-MON-RR'),'A','003519','SFMSTEST','SFMSTEST');
Insert into FM12SENXREF (NUXREFSN,DTTXNORIGIN,DTTXNUPDATE,CDSTATUS,NUSENATE,NATXNORGUSER,NATXNUPDUSER) values (3357, to_date('22-MAR-99','DD-MON-RR'),to_date('22-MAR-99','DD-MON-RR'),'A','003520','SFMSTEST','SFMSTEST');
Insert into FM12SENXREF (NUXREFSN,DTTXNORIGIN,DTTXNUPDATE,CDSTATUS,NUSENATE,NATXNORGUSER,NATXNUPDUSER) values (3358, to_date('22-MAR-99','DD-MON-RR'),to_date('22-MAR-99','DD-MON-RR'),'A','003521','SFMSTEST','SFMSTEST');


Insert into FD12ISSUE(NUXREFSN, NUXREFCO, DTLSTINVNTRY, DTTXNORIGIN, DTISSUE, DTTXNUPDATE, CDSTATUS, NATXNORGUSER, NATXNUPDUSER, CDLOCTYPEFRM, CDLOCTYPETO,CDLOCATTO,CDLOCATFROM,NUSERIAL,DTORIGTAG) values (700, 200, to_date('22-MAR-99','DD-MON-RR'),to_date('22-MAR-99','DD-MON-RR'), to_date('22-MAR-99','DD-MON-RR'),to_date('22-MAR-99','DD-MON-RR'),'A','INVENTORY','INVENTORY','W','W','A42FB','L711B','100Ad888ssd7f111', to_date('22-MAR-99','DD-MON-RR'));
Insert into FD12ISSUE(NUXREFSN, NUXREFCO, DTLSTINVNTRY, DTTXNORIGIN, DTISSUE, DTTXNUPDATE, CDSTATUS, NATXNORGUSER, NATXNUPDUSER, CDLOCTYPEFRM, CDLOCTYPETO,CDLOCATTO,CDLOCATFROM,NUSERIAL,DTORIGTAG) values (701, 200, to_date('22-MAR-99','DD-MON-RR'),to_date('22-MAR-99','DD-MON-RR'),to_date('22-MAR-99','DD-MON-RR'), to_date('22-MAR-99','DD-MON-RR'),'A','INVENTORY','INVENTORY','W','W','A42FB','L711B','83JdDi6771', to_date('22-MAR-99','DD-MON-RR'));
Insert into FD12ISSUE(NUXREFSN, NUXREFCO, DTLSTINVNTRY, DTTXNORIGIN, DTISSUE, DTTXNUPDATE, CDSTATUS, NATXNORGUSER, NATXNUPDUSER, CDLOCTYPEFRM, CDLOCTYPETO,CDLOCATTO,CDLOCATFROM,NUSERIAL,DTORIGTAG) values (702, 200, to_date('22-MAR-99','DD-MON-RR'),to_date('22-MAR-99','DD-MON-RR'),to_date('22-MAR-99','DD-MON-RR'), to_date('22-MAR-99','DD-MON-RR'),'A','INVENTORY','INVENTORY','W','W','A42FB','CAP125','UUU38919DdD78', to_date('22-MAR-99','DD-MON-RR'));
Insert into FD12ISSUE(NUXREFSN, NUXREFCO, DTLSTINVNTRY, DTTXNORIGIN, DTISSUE, DTTXNUPDATE, CDSTATUS, NATXNORGUSER, NATXNUPDUSER, DTORIGTAG) values (703, 200, to_date('22-MAR-99','DD-MON-RR'),to_date('22-MAR-99','DD-MON-RR'), to_date('22-MAR-99','DD-MON-RR'),to_date('22-MAR-99','DD-MON-RR'),'A','INVENTORY','INVENTORY', to_date('22-MAR-99','DD-MON-RR'));
Insert into FD12ISSUE(NUXREFSN, NUXREFCO, DTLSTINVNTRY, DTTXNORIGIN, DTISSUE, DTTXNUPDATE, CDSTATUS, NATXNORGUSER, NATXNUPDUSER, DTORIGTAG) values (3354, 203, to_date('22-MAR-99','DD-MON-RR'),to_date('22-MAR-99','DD-MON-RR'), to_date('22-MAR-99','DD-MON-RR'),to_date('22-MAR-99','DD-MON-RR'),'A','INVENTORY','INVENTORY', to_date('22-MAR-99','DD-MON-RR'));
Insert into FD12ISSUE(NUXREFSN, NUXREFCO, DTLSTINVNTRY, DTTXNORIGIN, DTISSUE, DTTXNUPDATE, CDSTATUS, NATXNORGUSER, NATXNUPDUSER, DTORIGTAG) values (3355, 203, to_date('22-MAR-99','DD-MON-RR'),to_date('22-MAR-99','DD-MON-RR'), to_date('22-MAR-99','DD-MON-RR'),to_date('22-MAR-99','DD-MON-RR'),'A','INVENTORY','INVENTORY', to_date('22-MAR-99','DD-MON-RR'));
Insert into FD12ISSUE(NUXREFSN, NUXREFCO, DTLSTINVNTRY, DTTXNORIGIN, DTISSUE, DTTXNUPDATE, CDSTATUS, NATXNORGUSER, NATXNUPDUSER, DTORIGTAG) values (3356, 203, to_date('22-MAR-99','DD-MON-RR'),to_date('22-MAR-99','DD-MON-RR'), to_date('22-MAR-99','DD-MON-RR'),to_date('22-MAR-99','DD-MON-RR'),'A','INVENTORY','INVENTORY', to_date('22-MAR-99','DD-MON-RR'));



Insert into FM12INVENTRY(NUXREFCO,DTTXNUPDATE,DTTXNORIGIN,CDSTATUS,CDLOCTYPE,CDLOCAT,NATXNUPDUSER,NATXNORGUSER,AMQTYOHSTD) values (201,to_date('23-MAR-99','DD-MON-RR'),to_date('22-MAR-99','DD-MON-RR'),'A','W','A42FB','INVENTORY','INVENTORY',3);
